# Generated by Django 2.0 on 2018-01-03 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots_scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='domain',
        ),
        migrations.AddField(
            model_name='useragent',
            name='website',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='robots_scraper.WebSite'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='user_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots_scraper.UserAgent'),
        ),
    ]
