# Generated by Django 2.0 on 2018-01-22 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots_scraper', '0002_auto_20180103_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='route',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots_scraper.Rule'),
        ),
    ]
